apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: burgerstands.restaurant.example.com
spec:
  group: restaurant.example.com
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                location:
                  type: string
                capacity:
                  type: integer
                isOpen:
                  type: boolean
  scope: Namespaced
  names:
    plural: burgerstands
    singular: burgerstand
    kind: BurgerStand
    shortNames:
      - bs